FROM golang as builder


ENV ENV=development
ENV VERSION=development

RUN git config --global url."https://oauth2:TxDhGZtUfS_xzS_Xn-T7@gitlab.com".insteadOf "https://gitlab.com"

WORKDIR /go/src/myapp

COPY . .

EXPOSE 8080